export const customerReviews = [
  {
    id: "1",
    name: "Paul L",
    designation: "Business Owner",
    companyName: "Luxe Interiors",
    avatar: "/avatars/paul-l.jpg",
    review: "Fantastic service! The team was responsive and delivered exactly what I needed on time. Good service and well-structured communication. Could improve response time a bit.",
    rating: 5,
    date: "2024-07-12",
  },
  {
    id: "2",
    name: "Sarah M",
    designation: "Marketing Manager",
    companyName: "BrightWave Media",
    avatar: "/avatars/sarah-m.jpg",
    review: "Very professional and easy to work with. The quality exceeded my expectations.",
    rating: 4.5,
    date: "2024-08-03",
  },
  {
    id: "3",
    name: "James Carter",
    designation: "Freelancer",
    companyName: "BrightBox Retail",
    avatar: "/avatars/james-carter.jpg",
    review: "Good experience overall. Communication was smooth and the final delivery was solid. Good service and well-structured communication. Could improve response time a bit.",
    rating: 4,
    date: "2024-06-25",
  },
  {
    id: "4",
    name: "Emily R",
    designation: "Product Manager",
    companyName: "TechNova Solutions",
    avatar: "/avatars/emily-r.jpg",
    review: "Absolutely amazing! Highly recommend. The attention to detail was incredible. Very professional and easy to work with. The quality exceeded my expectations.",
    rating: 5,
    date: "2024-09-10",
  },
  {
    id: "5",
    name: "Michael B",
    designation: "HR Lead",
    companyName: "GreenLeaf Corp",
    avatar: "/avatars/michael-b.jpg",
    review: "Great customer support and seamless process. Will work with them again.",
    rating: 4.7,
    date: "2024-10-01",
  },
  {
    id: "6",
    name: "Olivia H",
    designation: "Operations Lead",
    companyName: "Skyline Logistics",
    avatar: "/avatars/olivia-h.jpg",
    review: "Impressed with the fast delivery and smooth workflow. Great team! Very professional and easy to work with. The quality exceeded my expectations.",
    rating: 5,
    date: "2024-09-18",
  },
  {
    id: "7",
    name: "Daniel W",
    designation: "Software Engineer",
    companyName: "CloudCore Systems",
    avatar: "/avatars/daniel-w.jpg",
    review: "Good service and well-structured communication. Could improve response time a bit.",
    rating: 4,
    date: "2024-08-22",
  },
  {
    id: "8",
    name: "Hannah P",
    designation: "UI/UX Designer",
    companyName: "PixelCraft Studio",
    avatar: "/avatars/hannah-p.jpg",
    review: "Loved the final outcome! The team really understood my design needs.",
    rating: 4.8,
    date: "2024-07-30",
  },
  {
    id: "9",
    name: "Robert D",
    designation: "Entrepreneur",
    companyName: "StartLab Innovations",
    avatar: "/avatars/robert-d.jpg",
    review: "Very satisfied. Clear communication and excellent delivery standards.",
    rating: 5,
    date: "2024-11-05",
  },
  {
    id: "10",
    name: "Sophia K",
    designation: "Project Coordinator",
    companyName: "NovaBuild",
    avatar: "/avatars/sophia-k.jpg",
    review: "They handled everything smoothly. Great attention to detail!",
    rating: 4.6,
    date: "2024-10-12",
  },
]
