import { TFilteredProductItem, TProduct } from "@/types";

export const productFilteredItems: TFilteredProductItem[] = [
      {
            id: "1",
            label: "All",
            value: "",
      },
      {
            id: "2",
            label: "Special",
            value: "special",
      },
      {
            id: "3",
            label: "Popular",
            value: "popular",
      },
      {
            id: "4",
            label: "New/Used",
            value: "new",
      },
      {
            id: "5",
            label: "Certified",
            value: "certified",
      },
];

export const products: TProduct[] = [
  {
    id: "1",
    title: "VDubDiag for VW Audi Skoda Seat",
    rating: 5,
    oldPrice: 89.99,
    newPrice: 79.99,
    isNew: false,
    isPopular: false,
    isSold: true,
    image: "/images/vdubdiag-diagnostic.jpg",
    category: "Diagnostic Tools",
    description: "Professional OBD2 diagnostic tool for VW, Audi, Skoda, and Seat vehicles",
  },
  {
    id: "2",
    title: "Premium Car Air Filter Kit",
    rating: 4.8,
    oldPrice: 45.99,
    newPrice: 34.99,
    isNew: true,
    isPopular: true,
    isSold: false,
    image: "/images/car-air-filter.jpg",
    category: "Filters & Maintenance",
    description: "High-performance reusable air filter with increased airflow capacity",
  },
  {
    id: "3",
    title: "LED Headlight Conversion Kit",
    rating: 4.9,
    oldPrice: 199.99,
    newPrice: 149.99,
    isNew: true,
    isPopular: true,
    isSold: false,
    image: "/images/led-headlights.jpg",
    category: "Lighting",
    description: "Bright LED headlight conversion kit with 6000K white light output",
  },
  {
    id: "4",
    title: "Universal Dash Cam 4K",
    rating: 4.7,
    oldPrice: 129.99,
    newPrice: 99.99,
    isNew: false,
    isPopular: false,
    isSold: false,
    image: "/images/dash-cam-4k.jpg",
    category: "Electronics",
    description: "4K ultra HD dash camera with night vision and GPS tracking",
  },
  {
    id: "5",
    title: "Ceramic Car Brake Pads",
    rating: 4.6,
    oldPrice: 79.99,
    newPrice: 59.99,
    isNew: false,
    isPopular: true,
    isSold: false,
    image: "/images/brake-pads.jpg",
    category: "Brakes & Safety",
    description: "Low-dust ceramic brake pads for smooth and quiet braking",
  },
  {
    id: "6",
    title: "High-Performance Engine Air Intake",
    rating: 4.8,
    oldPrice: 159.99,
    newPrice: 119.99,
    isNew: true,
    isPopular: true,
    isSold: false,
    image: "/images/intake-system.jpg",
    category: "Performance",
    description: "Cold air intake system for increased horsepower and torque",
  },
  {
    id: "7",
    title: "Professional OBD2 Scanner",
    rating: 4.7,
    oldPrice: 99.99,
    newPrice: 79.99,
    isNew: false,
    isPopular: true,
    isSold: false,
    image: "/images/obd2-scanner.jpg",
    category: "Diagnostic Tools",
    description: "Full-featured OBD2 scanner with live data and DTC reading",
  },
  {
    id: "8",
    title: "Car Floor Mats Premium Set",
    rating: 4.5,
    oldPrice: 69.99,
    newPrice: 49.99,
    isNew: false,
    isPopular: true,
    isSold: false,
    image: "/images/floor-mats.jpg",
    category: "Interior",
    description: "Custom-fit premium floor mats with rubber backing for all seasons",
  },
  {
    id: "9",
    title: "Portable Car Jump Starter",
    rating: 4.9,
    oldPrice: 119.99,
    newPrice: 89.99,
    isNew: true,
    isPopular: true,
    isSold: false,
    image: "/images/jump-starter.jpg",
    category: "Emergency & Tools",
    description: "Compact 1000A peak current jump starter with USB power bank",
  },
  {
    id: "10",
    title: "Car Window Tinting Film",
    rating: 4.4,
    oldPrice: 39.99,
    newPrice: 29.99,
    isNew: false,
    isPopular: true,
    isSold: false,
    image: "/images/window-tint.jpg",
    category: "Exterior",
    description: "UV-blocking ceramic window tint film for UV protection and heat reduction",
  },
  {
    id: "11",
    title: "Premium Microfiber Seat Covers",
    rating: 4.6,
    oldPrice: 149.99,
    newPrice: 119.99,
    isNew: true,
    isPopular: true,
    isSold: false,
    image: "/images/seat-covers.jpg",
    category: "Interior",
    description: "Waterproof microfiber seat covers for ultimate protection and comfort",
  },
  {
    id: "12",
    title: "Digital Tire Pressure Gauge",
    rating: 4.8,
    oldPrice: 24.99,
    newPrice: 17.99,
    isNew: false,
    isPopular: true,
    isSold: false,
    image: "/images/tire-gauge.jpg",
    category: "Maintenance",
    description: "Accurate digital tire pressure gauge with LCD display and backlight",
  },
]
