import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import ContactHeader from "@/components/ui/ContactHeader";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { CartWishlistProvider } from "@/Providers/CartWishlistProvider";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-geist-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Mini EComrz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased font-poppins bg-primary`}
      >
        <CartWishlistProvider>
          <ContactHeader />
          <div className="sticky top-0 z-50 shadow-md">
            <Suspense fallback={null}>
              <Navbar />
            </Suspense>
          </div>
          {children}
          <Footer />
          <Toaster position="top-right" />
        </CartWishlistProvider>
      </body>
    </html>
  );
}
